#!/bin/bash

SCRIPTDIR=`dirname $0`

function usage {
	echo "USAGE:"
	echo $0 [IMDB ID] [video file]

}

if [ $# != 2 ]; then
	echo "ERROR: wrong number of arguments"
	usage
fi

# Remove any symbolic links from file name (allows link from home directory to /var/www/html/media/video -- with xml file containing correct path)

REALPATH=$(readlink -f -m "${2}")

${SCRIPTDIR}/imdbdataget.pl "$1" "$REALPATH" > "${REALPATH}.xml"

${SCRIPTDIR}/update-video-xml

