#!/bin/bash

SCRIPTDIR=`dirname $0`

function usage {
	echo "USAGE:"
	echo $0 [IMDB ID] [video file]

}

# output info on the movie just added
function output {

	echo "Title:   "`grep \<origtitle\> "${REALPATH}.xml" | sed 's/.*<origtitle>\(.*\)<\/origtitle>/\1/'`
	echo "Year:    "`grep \<year\> "${REALPATH}.xml" | sed 's/.*<year>\(.*\)<\/year>/\1/'`
	echo "Rating:  "`grep \<mpaa\> "${REALPATH}.xml" | sed 's/.*<mpaa>\(.*\)<\/mpaa>/\1/'`

}

if [ $# != 2 ]; then
	echo "ERROR: wrong number of arguments"
	usage
fi

# Remove any symbolic links from file name (allows link from home directory to /var/www/html/media/video -- with xml file containing correct path)

REALPATH=$(readlink -f -m "${2}")

${SCRIPTDIR}/imdbdataget.pl "$1" "$REALPATH" > "${REALPATH}.xml"

${SCRIPTDIR}/update-video-xml

output

